version: 2
jobs:
  amzlinux-python3.6.8:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          name:
          command: |
            sudo bash bin/packer-build.sh amzlinux-python3.6.8
workflows:
  version: 2
  my-workflow:
    jobs:
      - amzlinux-python3.6.8
